    placebo_pass = adjusted_placebo is not None and adjusted_placebo <= PREREGISTERED_CRYPTO_PROTOCOL.multiple_testing_alpha
    stress_pass = all(result.net_mean_bps > 0.0 for result in stress_results.values()) if stress_results else False
    group_sample_pass = all(
        metric.n >= config.min_group_rows
        for metric in list(stability_by_symbol.values())
        + list(stability_by_horizon.values())
    )
    fold_consistency_pass = (
        fold_baseline_pass_fraction >= config.min_fold_pass_fraction
        and fold_economic_positive_fraction >= config.min_fold_pass_fraction
    )
    promotion_eligible = bool(
        minimum_fold_count
        and len(oos_labels) >= config.test_rows
        and baseline_beat
        and economic_positive
        and explicit_friction_pass
        and placebo_pass
        and stress_pass
        and research_status == "PASS"
        and group_sample_pass
        and fold_consistency_pass
        and temporal.passed
    )
    return ValidationReport(
        status="OOS_EVALUATED",
        dataset_rows=len(dataset),
        folds=tuple(fold_evaluations),
        fold_baseline_pass_fraction=fold_baseline_pass_fraction,
        fold_economic_positive_fraction=fold_economic_positive_fraction,
        temporal_stability=temporal,
        oos_probabilities=tuple(oos_probabilities),
        oos_labels=tuple(oos_labels),
        oos_returns_bps=tuple(oos_returns),
        placebo_p_value=placebo_p,
        placebo_iterations=placebo_n,
        stability_by_symbol=stability_by_symbol,
        stability_by_horizon_ms=stability_by_horizon,
        stress_results=stress_results,
        multiple_testing_p_value=adjusted_placebo,
        dsr_p_value=dsr.adjusted_p_value,
        pbo=pbo_value,
        research_robustness_status=research_status,
        research_robustness_reasons=tuple(research_reasons),
        promotion_eligible=promotion_eligible,
    )


def validation_run_id(
    *,
    replay_fingerprint: str,
    model_id: str,
    model_version: str,
    target_spec: ForecastTargetSpec,
    config: WalkForwardConfig,
    policy: EconomicPolicySpec,
) -> str:
    identity = {
        "replay_fingerprint": replay_fingerprint,
        "protocol_hash": PREREGISTERED_CRYPTO_PROTOCOL.protocol_hash,
        "study_id": PREREGISTERED_CRYPTO_PROTOCOL.study_id,
        "model_id": model_id,
        "model_version": model_version,
        "target_horizon_ms": target_spec.horizon_ms,
        "target_kind": target_spec.kind,
        "walk_forward": asdict(config),
        "economic_policy": asdict(policy),
    }
    return hashlib.sha256(
        json.dumps(identity, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()[:32]


def persist_validation_report(
    store,
    report: ValidationReport,
    dataset: Sequence[ForecastDatasetRow],
    *,
    replay_fingerprint: str,
    target_spec: ForecastTargetSpec,
    config: WalkForwardConfig,
    policy: EconomicPolicySpec,
    model_id: str,
    model_version: str,
) -> dict[str, int | str | bool]:
    """Persist immutable research evidence generated by one OOS validation run."""
    from .storage import CryptoStore

    if not isinstance(store, CryptoStore):
        raise TypeError("store must be a CryptoStore")
    target_spec.validate()
    config.validate()
    policy.validate()