from fastapi.responses import HTMLResponse

HTML = HTMLResponse(r"""<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#050607">
<title>GORILA ARGENTUM · Signal Terminal</title>
<style>
:root{--bg:#050607;--panel:#0a0d10;--line:#1a232a;--line2:#2b3943;--text:#eef5f8;--muted:#84929b;--dim:#53616b;--cyan:#6be3ff;--green:#55e4aa;--amber:#e8bd68;--red:#ff6d82}
*{box-sizing:border-box}html,body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}
body{background:radial-gradient(1000px 520px at 70% -15%,rgba(26,107,142,.17),transparent 62%),linear-gradient(180deg,#050607,#07090b 70%,#050607)}
button,select{font:inherit}.top{position:sticky;top:0;z-index:30;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:11px 14px;border-bottom:1px solid var(--line);background:rgba(5,6,7,.95);backdrop-filter:blur(12px)}
.brand{display:flex;align-items:center;gap:10px;min-width:0}.g{font-size:31px;font-weight:950;color:var(--cyan)}.name{font-size:14px;font-weight:950;letter-spacing:.14em}.sub{font-size:7px;color:var(--dim);letter-spacing:.12em;text-transform:uppercase;margin-top:3px}
.topbar{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.chip{padding:6px 9px;border:1px solid var(--line2);border-radius:999px;background:#080a0c;color:#b6c2c8;font-size:8px;font-weight:900;letter-spacing:.08em}.chip.good{border-color:#255a44;color:#a9f2d1}.chip.warn{border-color:#67502b;color:#f2d48f}.chip.bad{border-color:#69303b;color:#ffafba}
.shell{max-width:1450px;margin:auto;padding:12px}.hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;border:1px solid var(--line2);border-radius:14px;background:#080a0d;padding:16px;box-shadow:0 18px 55px rgba(0,0,0,.22)}
.kicker{font-size:8px;color:var(--cyan);font-weight:950;letter-spacing:.18em;text-transform:uppercase}.hero h1{margin:5px 0 4px;font-size:27px;letter-spacing:-.03em}.hero p{margin:0;color:var(--muted);font-size:10px;line-height:1.55;max-width:950px}
.sessionBox{min-width:235px;border:1px solid var(--line);border-radius:11px;background:#07090b;padding:12px}.sessionTop{display:flex;justify-content:space-between;align-items:center}.sessionTitle{font-size:8px;color:var(--dim);letter-spacing:.1em;text-transform:uppercase}.sessionVal{font-size:15px;font-weight:950;margin-top:4px}.sessionMeta{margin-top:6px;color:var(--muted);font-size:9px;line-height:1.45}
.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.btn,select{background:#080b0e;border:1px solid var(--line2);color:#dbe7ec;border-radius:8px;padding:8px 10px;font-size:10px;font-weight:850}.btn{cursor:pointer}.auto{color:var(--muted);font-size:9px;display:flex;align-items:center;gap:6px}input{accent-color:var(--cyan)}
.sectionHead{display:flex;justify-content:space-between;align-items:end;gap:8px;margin:12px 0 8px}.sectionTitle{font-size:10px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.sectionSub{font-size:8px;color:var(--dim)}
.matrix{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.tile{border:1px solid var(--line2);border-radius:12px;background:#080a0d;padding:12px;cursor:pointer}.tile.sel{border-color:#41829a;box-shadow:0 0 0 1px #1b475a inset}.tileTop{display:flex;justify-content:space-between;align-items:start;gap:10px}.sym{font-size:17px;font-weight:950}.sig{font-size:9px;font-weight:950;letter-spacing:.08em;padding:5px 8px;border-radius:999px;border:1px solid var(--line2)}.sig.up{color:var(--green);border-color:#255b45}.sig.down{color:var(--red);border-color:#66303c}.sig.neutral{color:var(--amber);border-color:#67512b}.sig.na{color:var(--muted)}
.scoreRow{display:grid;grid-template-columns:1fr 74px;gap:9px;margin-top:10px;align-items:center}.scoreLabel{font-size:7px;color:var(--dim);letter-spacing:.1em;text-transform:uppercase}.bar{height:7px;border-radius:99px;background:#11171c;overflow:hidden;border:1px solid #1b242a}.bar i{display:block;height:100%;background:linear-gradient(90deg,#244e60,#69e1ff);border-radius:99px}.score{font-size:20px;font-weight:950;text-align:right}.tileGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.mini{border:1px solid var(--line);border-radius:8px;padding:8px;background:#07090b}.mini small{display:block;font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}.mini b{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis}.tileFoot{display:flex;justify-content:space-between;gap:8px;margin-top:9px;font-size:8px;color:var(--muted)}
.detail{margin-top:12px;border:1px solid var(--line2);border-radius:14px;background:#080a0d;overflow:hidden}.detailHead{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:12px 14px;border-bottom:1px solid var(--line)}.detailTitle{font-size:11px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.detailBody{padding:14px}.detailGrid{display:grid;grid-template-columns:1.35fr .65fr;gap:10px}.primary{border:1px solid var(--line2);border-radius:11px;background:#07090b;padding:14px}.primaryTop{display:flex;justify-content:space-between;gap:12px;align-items:end}.price{font-size:39px;font-weight:950}.priceMeta{font-size:8px;color:var(--muted);margin-top:3px}.forecast{text-align:right}.forecastLabel{font-size:7px;color:var(--dim);letter-spacing:.09em;text-transform:uppercase}.forecastSignal{font-size:29px;font-weight:950;margin-top:2px}.prob{font-size:11px;color:var(--muted)}.goodText{color:var(--green)}.badText{color:var(--red)}.warnText{color:var(--amber)}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.kpi{border:1px solid var(--line);border-radius:9px;padding:9px;background:#07090b}.kpi small{display:block;font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}.kpi b{display:block;font-size:15px;margin-top:4px}
.detailCols{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:9px}.box{border:1px solid var(--line);border-radius:10px;background:#07090b;padding:11px}.box h3{margin:0 0 5px;font-size:8px;letter-spacing:.09em;text-transform:uppercase}.row{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #151c21;font-size:9px}.row:last-child{border-bottom:0}.muted{color:var(--muted)}
.horizon{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.h{border:1px solid var(--line2);border-radius:8px;background:#080b0e;padding:7px 8px;font-size:8px}.h b{font-size:10px;margin-left:4px}
.bottomGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:8px}.table th,.table td{padding:8px;border-bottom:1px solid #151c21;text-align:left;white-space:nowrap}.table th{font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}
pre{margin:0;background:#06080a;border:1px solid var(--line);border-radius:9px;padding:9px;color:#91a0a8;font:8px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;max-height:220px;overflow:auto}.footer{padding:12px 2px 18px;color:#46535c;font-size:7px;letter-spacing:.07em;text-transform:uppercase;display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap}
@media(max-width:1100px){.matrix{grid-template-columns:repeat(2,minmax(0,1fr))}.detailGrid{grid-template-columns:1fr}.bottomGrid{grid-template-columns:1fr}}
@media(max-width:700px){.top{align-items:flex-start;flex-direction:column;gap:8px}.topbar{width:100%;justify-content:flex-start;overflow:auto;flex-wrap:nowrap}.chip{flex:0 0 auto}.hero{grid-template-columns:1fr}.sessionBox{min-width:0}.shell{padding:9px}.hero{padding:13px}.hero h1{font-size:23px}.hero p{font-size:11px}.matrix{grid-template-columns:1fr}.tile{padding:11px}.tileGrid{grid-template-columns:repeat(2,1fr)}.kpis{grid-template-columns:repeat(2,1fr)}.detailCols{grid-template-columns:1fr}.price{font-size:34px}.forecastSignal{font-size:25px}.toolbar{margin-top:8px}.btn,select{font-size:11px;padding:9px 11px}.auto{font-size:10px}.table table{font-size:9px}.table th{font-size:8px}}
</style>
</head>
<body>
<header class="top">
<div class="brand"><div class="g">G</div><div><div class="name">GORILA ARGENTUM</div><div class="sub">advanced research signal terminal · Argentina</div></div></div>
<div class="topbar"><span id="live" class="chip">CONNECTING</span><span id="session" class="chip">BYMA · —</span><span id="storage" class="chip">POSTGRES · —</span><span id="gate" class="chip bad">GATE · BLOCKED</span><button id="refresh" class="btn">REFRESH</button><a class="btn" href="/docs">API</a></div>
</header>
<main class="shell">
<section class="hero"><div>
<div class="kicker">Primary research instrument</div><h1>ARGENTINA SIGNAL MATRIX</h1>
<p>Señal de investigación auditable para renta variable argentina. La fuerza de señal combina probabilidad del motor, evidencia OOS, consenso multihorizonte, frescura de datos, shadow outcomes y drift. No concede autoridad de ejecución.</p>
<div class="toolbar"><select id="ticker"></select><button id="hardRefresh" class="btn">RECALCULATE</button><label class="auto"><input id="auto" type="checkbox" checked> refresh 5 s</label><span id="matrixMeta" class="chip">MATRIX · —</span></div>
</div>
<div class="sessionBox"><div class="sessionTop"><div class="sessionTitle">BYMA session</div><span id="sessionBadge" class="chip">—</span></div><div id="sessionValue" class="sessionVal">—</div><div id="sessionMeta" class="sessionMeta">—</div></div>
</section>

<div class="sectionHead"><div><div class="sectionTitle">Universe · GGAL · BMA · YPFD · PAMP · TGSU2 · CEPU</div><div class="sectionSub">selecciona una tarjeta para abrir la telemetría completa</div></div><div id="matrixTime" class="sectionSub">—</div></div>
<section id="matrix" class="matrix"></section>

<section class="detail"><div class="detailHead"><div><div class="detailTitle">Signal detail</div><div id="detailSub" class="sectionSub">—</div></div><span id="detailState" class="sig neutral">—</span></div><div class="detailBody">
<div class="detailGrid">
<div class="primary"><div class="primaryTop"><div><div id="dSymbol" class="sym">—</div><div id="dPrice" class="price">—</div><div id="dPriceMeta" class="priceMeta">—</div></div><div class="forecast"><div class="forecastLabel">Research signal</div><div id="dSignal" class="forecastSignal">—</div><div id="dProb" class="prob">P(UP) —</div></div></div>
<div class="kpis"><div class="kpi"><small>Signal score</small><b id="dScore">—</b></div><div class="kpi"><small>Confidence</small><b id="dConf">—</b></div><div class="kpi"><small>Edge</small><b id="dEdge">—</b></div><div class="kpi"><small>Data grade</small><b id="dGrade">—</b></div></div>
<div class="detailCols"><div class="box"><h3>Market state</h3><div class="row"><span class="muted">Bid / Ask</span><b id="dBidAsk">—</b></div><div class="row"><span class="muted">Spread</span><b id="dSpread">—</b></div><div class="row"><span class="muted">Data age</span><b id="dAge">—</b></div><div class="row"><span class="muted">Source</span><b id="dSource">—</b></div><div class="row"><span class="muted">Quote time</span><b id="dQuoteTime">—</b></div></div>
<div class="box"><h3>Structure</h3><div class="row"><span class="muted">1 bar</span><b id="m1">—</b></div><div class="row"><span class="muted">3 bars</span><b id="m3">—</b></div><div class="row"><span class="muted">5 bars</span><b id="m5">—</b></div><div class="row"><span class="muted">10 bars</span><b id="m10">—</b></div><div class="row"><span class="muted">Trend Z</span><b id="mTrend">—</b></div></div></div>
<div class="box" style="margin-top:9px"><h3>Multi-horizon consensus</h3><div id="horizons" class="horizon"></div></div>
</div>
<div class="box"><h3>Precision evidence</h3><div class="row"><span class="muted">OOS status</span><b id="vStatus">—</b></div><div class="row"><span class="muted">Accuracy</span><b id="vAcc">—</b></div><div class="row"><span class="muted">Brier</span><b id="vBrier">—</b></div><div class="row"><span class="muted">Brier skill</span><b id="vSkill">—</b></div><div class="row"><span class="muted">Log loss</span><b id="vLogloss">—</b></div><div class="row"><span class="muted">OOS N</span><b id="vN">—</b></div><h3 style="margin-top:14px">Risk controls</h3><div class="row"><span class="muted">Drift</span><b id="rDrift">—</b></div><div class="row"><span class="muted">PSI</span><b id="rPsi">—</b></div><div class="row"><span class="muted">Shadow accuracy</span><b id="rShadow">—</b></div><div id="flags" style="margin-top:8px"></div></div>
</div></div></section>

<section class="bottomGrid"><div class="box"><h3>System state</h3><div class="row"><span class="muted">Runtime tick</span><b id="runtime">—</b></div><div class="row"><span class="muted">Autonomous cycle</span><b id="autonomous">—</b></div><div class="row"><span class="muted">Circuit breaker</span><b id="circuit">—</b></div><div class="row"><span class="muted">Shadow</span><b id="shadow">—</b></div><div class="row"><span class="muted">Promotion</span><b id="promotion">—</b></div></div>
<div class="box"><h3>Data fabric</h3><div class="table"><table><thead><tr><th>source</th><th>status</th><th>rows</th><th>latency</th><th>last success</th></tr></thead><tbody id="sources"></tbody></table></div></div></section>
<section class="box" style="margin-top:12px"><h3>Runtime telemetry</h3><pre id="telemetry">{}</pre></section>
<footer class="footer"><span>RESEARCH ONLY · TRADING EXECUTION DISABLED · AUTOMATIC PROMOTION OFF</span><span>DRIFT MONITOR · CONTROL ROOM — BATCH 13 · SHADOW LEDGER — BATCH 14</span></footer>
</main>
<script>
const $=id=>document.getElementById(id);
const fmt=(v,d=3)=>v===null||v===undefined||v===''?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=(v,d=1)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':(Number(v)*100).toFixed(d)+'%';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let selected='GGAL',matrixTimer=null,detailTimer=null,controlTimer=null,alphaMap={};
async function json(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error('Non-JSON '+url)}if(!r.ok)throw new Error(d.detail||('HTTP '+r.status));return d}
function chip(el,text,kind){el.textContent=text;el.className='chip '+(kind||'')}
function stateClass(signal){return signal==='UP'?'up':signal==='DOWN'?'down':signal==='NEUTRAL'?'neutral':'na'}
function renderSession(m){const s=m?.argentina_session||{};const open=!!s.open;chip($('session'),'BYMA · '+(open?'OPEN':'CLOSED'),open?'good':'warn');chip($('sessionBadge'),open?'OPEN':'CLOSED',open?'good':'warn');$('sessionValue').textContent=open?'NEGOCIACIÓN ABIERTA':'MERCADO CERRADO';$('sessionMeta').textContent=(s.local_time||'—')+' · '+(s.regular_window?.open||'—')+'–'+(s.regular_window?.close||'—')}
function tile(item){const sel=item.symbol===selected?' sel':'';const sig=stateClass(item.signal);const score=Number(item.signal_score||0);const p=item.probability?.up;const age=item.market?.engine_age_seconds;const grade=item.market?.data_grade||'—';const a=alphaMap[item.symbol]||{};return '<div class="tile'+sel+'" data-symbol="'+esc(item.symbol)+'"><div class="tileTop"><div><div class="sym">'+esc(item.symbol)+'</div><div style="font-size:7px;color:#53616b;letter-spacing:.08em;text-transform:uppercase;margin-top:2px">V2 relative alpha</div></div><span class="sig '+sig+'">'+esc(item.signal||'—')+'</span></div><div class="scoreRow"><div><div class="scoreLabel">research signal score</div><div class="bar"><i style="width:'+Math.max(0,Math.min(100,score))+'%"></i></div></div><div class="score">'+score.toFixed(1)+'</div></div><div class="tileGrid"><div class="mini"><small>P(UP)</small><b>'+pct(p)+'</b></div><div class="mini"><small>V2 P(RES UP)</small><b>'+pct(a.p_residual_up)+'</b></div><div class="mini"><small>V2 RANK</small><b>'+(a.rank??'—')+'</b></div><div class="mini"><small>DATA</small><b>'+esc(grade)+'</b></div></div><div class="tileFoot"><span>'+esc(a.direction||item.status||'—')+'</span><span>age '+(age==null?'—':fmt(age,0)+'s')+'</span></div></div>'}
function renderMatrix(m){const items=m.items||[];if(!items.some(x=>x.symbol===selected)&&items.length)selected=items[0].symbol;$('ticker').innerHTML=items.map(x=>'<option>'+esc(x.symbol)+'</option>').join('');$('ticker').value=selected;$('matrix').innerHTML=items.map(tile).join('');[...document.querySelectorAll('.tile')].forEach(el=>el.addEventListener('click',()=>{selected=el.dataset.symbol;$('ticker').value=selected;refreshDetail()}));const c=m.counts||{};$('matrixMeta').textContent='MATRIX · '+(c.total??items.length)+' · WATCH '+(c.watch??0)+' · BLOCKED '+(c.blocked??0);$('matrixTime').textContent='updated '+new Date().toLocaleTimeString();renderSession(m)}
function renderDetail(d){$('dSymbol').textContent=d.symbol||'—';$('dPrice').textContent=fmt(d.market?.last,4);$('dPriceMeta').textContent=(d.market?.source||'—')+' · '+(d.market?.quote_timestamp||'—');const sig=d.signal||'—';$('dSignal').textContent=sig;$('dSignal').className='forecastSignal '+(sig==='UP'?'goodText':sig==='DOWN'?'badText':sig==='NEUTRAL'?'warnText':'');$('dProb').textContent='P(UP) '+pct(d.probability?.up)+' · P(DOWN) '+pct(d.probability?.down);$('dScore').textContent=fmt(d.signal_score,1);$('dConf').textContent=pct(d.probability?.confidence);$('dEdge').textContent=pct(d.probability?.edge);$('dGrade').textContent=d.market?.data_grade||'—';$('dBidAsk').textContent=fmt(d.market?.bid,4)+' / '+fmt(d.market?.ask,4);$('dSpread').textContent=fmt(d.market?.spread_bps,2)+' bps';$('dAge').textContent=d.market?.engine_age_seconds==null?'—':fmt(d.market.engine_age_seconds,1)+' s';$('dSource').textContent=d.market?.source||'—';$('dQuoteTime').textContent=d.market?.quote_timestamp||'—';const st=d.structure||{};$('m1').textContent=pct(st.return_1,2);$('m3').textContent=pct(st.return_3,2);$('m5').textContent=pct(st.return_5,2);$('m10').textContent=pct(st.return_10,2);$('mTrend').textContent=fmt(st.trend_z,2);const h=d.multi_horizon?.horizons||{};$('horizons').innerHTML=Object.entries(h).map(([k,x])=>'<div class="h">'+esc(k)+'s <b>'+pct(x?.latest_forecast?.p_up)+'</b></div>').join('')||'<div class="h">—</div>';$('vStatus').textContent=d.validation?.validated?'VALIDATED':'RESEARCH / NOT VALIDATED';$('vStatus').className=d.validation?.validated?'goodText':'warnText';$('vAcc').textContent=pct(d.validation?.accuracy);$('vBrier').textContent=fmt(d.validation?.brier,5);$('vSkill').textContent=fmt(d.validation?.brier_skill,5);$('vLogloss').textContent=fmt(d.validation?.log_loss,5);$('vN').textContent=fmt(d.validation?.oos_count,0);$('rDrift').textContent=d.drift?.status||'—';$('rPsi').textContent=fmt(d.drift?.psi,2);$('rShadow').textContent=pct(d.shadow?.accuracy);const flags=d.risk_flags||[];$('flags').innerHTML=flags.length?flags.map(f=>'<div class="row"><span class="muted">flag</span><b class="badText">'+esc(f)+'</b></div>').join(''):'<div class="row"><span class="muted">flags</span><b class="goodText">NONE</b></div>';$('detailState').textContent=d.status||'—';$('detailState').className='sig '+stateClass(d.signal);$('detailSub').textContent='research-only · '+(d.actionable?'armed research':'not actionable')}
async function refreshMatrix(){try{const d=await json('/api/gorila/signal-matrix');let a=null;try{a=await json('/api/gorila/cross-sectional')}catch(v2e){a=null;$('telemetry').textContent='V2 endpoint unavailable: '+String(v2e)}alphaMap={};(a?.items||[]).forEach(x=>alphaMap[x.symbol]=x);renderMatrix(d);chip($('live'),'ONLINE','good');chip($('matrixMeta'),(a?.evidence?.validation_status||'V2 UNKNOWN')+' · V2 5D',a?.evidence?.validation_status==='VALIDATED_RESEARCH'?'good':'warn')}catch(e){chip($('live'),'ERROR','bad');$('telemetry').textContent=String(e)}}
async function refreshDetail(){try{renderDetail(await json('/api/gorila/signal/'+encodeURIComponent(selected)))}catch(e){$('detailSub').textContent=String(e)}}
async function refreshControl(){try{const s=await json('/api/gorila/control'),h=s.health||{},p=s.promotion?.current_evaluation||{},sh=s.shadow||{},rt=(s.runtime?.items||[])[0];chip($('storage'),h.database?.ready?'POSTGRES · READY':'POSTGRES · DEGRADED',h.database?.ready?'good':'bad');chip($('gate'),'GATE · '+(p.status||'BLOCKED'),p.status==='ELIGIBLE'?'good':'bad');$('runtime').textContent=rt?.status||'—';$('autonomous').textContent=h.autonomous_runtime?.status||'—';const readiness=(rt?.result?.audit||{}).readiness||{};$('circuit').textContent=readiness.circuit_breaker||'—';$('shadow').textContent=(sh.settled??0)+' settled / '+(sh.predictions??0)+' total · '+pct(sh.accuracy);$('promotion').textContent=p.status||'BLOCKED';$('sources').innerHTML=(h.sources||[]).map(x=>'<tr><td>'+esc(x.source)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.rows_last_batch)+'</td><td>'+fmt(x.latency_ms,1)+' ms</td><td>'+esc(x.last_success_at||'—')+'</td></tr>').join('');$('telemetry').textContent=JSON.stringify({health:h,promotion:s.promotion,shadow:sh,runtime:s.runtime},null,2)}catch(e){$('telemetry').textContent=String(e)}}
$('ticker').addEventListener('change',e=>{selected=e.target.value;refreshDetail()});$('hardRefresh').addEventListener('click',()=>{refreshMatrix();refreshDetail();refreshControl()});$('refresh').addEventListener('click',()=>{refreshMatrix();refreshDetail();refreshControl()});$('auto').addEventListener('change',e=>{for(const t of [matrixTimer,detailTimer,controlTimer])if(t)clearInterval(t);matrixTimer=detailTimer=controlTimer=null;if(e.target.checked){matrixTimer=setInterval(refreshMatrix,5000);detailTimer=setInterval(refreshDetail,5000);controlTimer=setInterval(refreshControl,10000)}});
(async()=>{await refreshMatrix();await refreshDetail();await refreshControl();matrixTimer=setInterval(refreshMatrix,5000);detailTimer=setInterval(refreshDetail,5000);controlTimer=setInterval(refreshControl,10000)})();
</script>
<!-- Compatibility markers preserved:
     /api/drift?limit=50
     /api/control
     /api/shadow/summary
     DRIFT MONITOR
     CONTROL ROOM — BATCH 13
     SHADOW LEDGER — BATCH 14
-->
</body></html>""")
