from fastapi.responses import HTMLResponse

HTML = HTMLResponse(r"""<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#050607">
<title>GORILA ARGENTUM · Signal Terminal</title>
<style>
:root{--bg:#050607;--panel:#0a0d10;--line:#1a232a;--line2:#2b3943;--text:#eef5f8;--muted:#84929b;--dim:#53616b;--cyan:#6be3ff;--green:#55e4aa;--amber:#e8bd68;--red:#ff6d82}
*{box-sizing:border-box}html,body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}
body{background:radial-gradient(1000px 520px at 70% -15%,rgba(26,107,142,.17),transparent 62%),linear-gradient(180deg,#050607,#07090b 70%,#050607)}
button,select{font:inherit}.top{position:sticky;top:0;z-index:30;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:11px 14px;border-bottom:1px solid var(--line);background:rgba(5,6,7,.95);backdrop-filter:blur(12px)}
.brand{display:flex;align-items:center;gap:10px;min-width:0}.g{font-size:31px;font-weight:950;color:var(--cyan)}.name{font-size:14px;font-weight:950;letter-spacing:.14em}.sub{font-size:7px;color:var(--dim);letter-spacing:.12em;text-transform:uppercase;margin-top:3px}
.topbar{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.chip{padding:6px 9px;border:1px solid var(--line2);border-radius:999px;background:#080a0c;color:#b6c2c8;font-size:8px;font-weight:900;letter-spacing:.08em}.chip.good{border-color:#255a44;color:#a9f2d1}.chip.warn{border-color:#67502b;color:#f2d48f}.chip.bad{border-color:#69303b;color:#ffafba}
.shell{max-width:1450px;margin:auto;padding:12px}.hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;border:1px solid var(--line2);border-radius:14px;background:#080a0d;padding:16px;box-shadow:0 18px 55px rgba(0,0,0,.22)}
.kicker{font-size:8px;color:var(--cyan);font-weight:950;letter-spacing:.18em;text-transform:uppercase}.hero h1{margin:5px 0 4px;font-size:27px;letter-spacing:-.03em}.hero p{margin:0;color:var(--muted);font-size:10px;line-height:1.55;max-width:950px}
.sessionBox{min-width:235px;border:1px solid var(--line);border-radius:11px;background:#07090b;padding:12px}.sessionTop{display:flex;justify-content:space-between;align-items:center}.sessionTitle{font-size:8px;color:var(--dim);letter-spacing:.1em;text-transform:uppercase}.sessionVal{font-size:15px;font-weight:950;margin-top:4px}.sessionMeta{margin-top:6px;color:var(--muted);font-size:9px;line-height:1.45}
.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.btn,select{background:#080b0e;border:1px solid var(--line2);color:#dbe7ec;border-radius:8px;padding:8px 10px;font-size:10px;font-weight:850}.btn{cursor:pointer}.auto{color:var(--muted);font-size:9px;display:flex;align-items:center;gap:6px}input{accent-color:var(--cyan)}
.sectionHead{display:flex;justify-content:space-between;align-items:end;gap:8px;margin:12px 0 8px}.sectionTitle{font-size:10px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.sectionSub{font-size:8px;color:var(--dim)}
.matrix{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.tile{border:1px solid var(--line2);border-radius:12px;background:#080a0d;padding:12px;cursor:pointer}.tile:active{transform:translateY(1px)}.tile.noData{opacity:.8}.sig.na{color:#84929b;border-color:#3a454c}.score{min-width:38px}.tile.sel{border-color:#41829a;box-shadow:0 0 0 1px #1b475a inset}.tileTop{display:flex;justify-content:space-between;align-items:start;gap:10px}.sym{font-size:17px;font-weight:950}.sig{font-size:9px;font-weight:950;letter-spacing:.08em;padding:5px 8px;border-radius:999px;border:1px solid var(--line2)}.sig.up{color:var(--green);border-color:#255b45}.sig.down{color:var(--red);border-color:#66303c}.sig.neutral{color:var(--amber);border-color:#67512b}.sig.na{color:var(--muted)}
.scoreRow{display:grid;grid-template-columns:1fr 74px;gap:9px;margin-top:10px;align-items:center}.scoreLabel{font-size:7px;color:var(--dim);letter-spacing:.1em;text-transform:uppercase}.bar{height:7px;border-radius:99px;background:#11171c;overflow:hidden;border:1px solid #1b242a}.bar i{display:block;height:100%;background:linear-gradient(90deg,#244e60,#69e1ff);border-radius:99px}.score{font-size:20px;font-weight:950;text-align:right}.tileGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.mini{border:1px solid var(--line);border-radius:8px;padding:8px;background:#07090b}.mini small{display:block;font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}.mini b{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis}.tileFoot{display:flex;justify-content:space-between;gap:8px;margin-top:9px;font-size:8px;color:var(--muted)}
.detail{margin-top:12px;border:1px solid var(--line2);border-radius:14px;background:#080a0d;overflow:hidden}.detailHead{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:12px 14px;border-bottom:1px solid var(--line)}.detailTitle{font-size:11px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.detailBody{padding:14px}.detailGrid{display:grid;grid-template-columns:1.35fr .65fr;gap:10px}.primary{border:1px solid var(--line2);border-radius:11px;background:#07090b;padding:14px}.primaryTop{display:flex;justify-content:space-between;gap:12px;align-items:end}.price{font-size:39px;font-weight:950}.priceMeta{font-size:8px;color:var(--muted);margin-top:3px}.forecast{text-align:right}.forecastLabel{font-size:7px;color:var(--dim);letter-spacing:.09em;text-transform:uppercase}.forecastSignal{font-size:29px;font-weight:950;margin-top:2px}.prob{font-size:11px;color:var(--muted)}.goodText{color:var(--green)}.badText{color:var(--red)}.warnText{color:var(--amber)}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.kpi{border:1px solid var(--line);border-radius:9px;padding:9px;background:#07090b}.kpi small{display:block;font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}.kpi b{display:block;font-size:15px;margin-top:4px}
.detailCols{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:9px}.box{border:1px solid var(--line);border-radius:10px;background:#07090b;padding:11px}.box h3{margin:0 0 5px;font-size:8px;letter-spacing:.09em;text-transform:uppercase}.row{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #151c21;font-size:9px}.row:last-child{border-bottom:0}.muted{color:var(--muted)}
.horizon{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.h{border:1px solid var(--line2);border-radius:8px;background:#080b0e;padding:7px 8px;font-size:8px}.h b{font-size:10px;margin-left:4px}
.matrix,.detail,.bottomGrid,.box{content-visibility:auto;contain-intrinsic-size:240px}
.diagnostics{margin-top:12px;border:1px solid var(--line2);border-radius:12px;background:#080a0d;overflow:hidden}
.diagnostics summary{list-style:none;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 13px;color:#b8c4ca;font-size:8px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}
.diagnostics summary::-webkit-details-marker{display:none}
.diagnostics summary:before{content:'+';display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border:1px solid var(--line2);border-radius:50%;color:var(--muted);font-size:12px;line-height:1}
.diagnostics[open] summary:before{content:'−'}
.diagnosticsTitle{display:flex;align-items:center;gap:8px}
.diagnosticsMeta{color:var(--dim);font-size:7px;letter-spacing:.08em;font-weight:850}
.diagnosticsBody{padding:0 12px 12px}

.chartCard{margin-top:12px;border:1px solid var(--line2);border-radius:14px;background:#080a0d;overflow:hidden}
.chartHeader{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 15px;border-bottom:1px solid var(--line);flex-wrap:wrap}
.chartIdentity{display:flex;align-items:baseline;gap:10px;min-width:0}
.chartSymbol{font-size:22px;font-weight:950;letter-spacing:-.03em}.chartLast{font-size:19px;font-weight:900}.chartMove{font-size:10px;font-weight:900}
.chartMove.up{color:var(--green)}.chartMove.down{color:var(--red)}.chartMove.flat{color:var(--muted)}
.chartControls{display:flex;align-items:center;gap:5px;flex-wrap:wrap}
.rangeBtn{border:1px solid var(--line2);background:#080b0e;color:#aebbc2;border-radius:7px;padding:7px 9px;font-size:8px;font-weight:950;letter-spacing:.06em;cursor:pointer}
.rangeBtn:hover{border-color:#3d5a68;color:#dff7ff}.rangeBtn.active{border-color:#3d7890;background:#0c2029;color:#c9f6ff}
.chartShell{height:360px;position:relative;background:linear-gradient(180deg,#06080a,#07090c)}
#priceCanvas{display:block;width:100%;height:100%;touch-action:none}
.chartTooltip{position:absolute;z-index:5;pointer-events:none;min-width:150px;padding:8px 9px;border:1px solid #32414b;border-radius:8px;background:rgba(5,7,9,.94);box-shadow:0 10px 30px rgba(0,0,0,.32);font-size:9px;line-height:1.35;color:#dbe6eb;backdrop-filter:blur(8px);display:none}
.chartTooltip b{font-size:11px}.chartTooltip small{display:block;color:#71808a;margin-top:2px}
.chartEmpty{position:absolute;inset:0;display:none;align-items:center;justify-content:center;color:#6e7c85;font-size:10px;letter-spacing:.08em;text-transform:uppercase}
.chartFooter{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;padding:9px 15px;border-top:1px solid var(--line);font-size:8px;color:var(--dim)}
.bottomGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:8px}.table th,.table td{padding:8px;border-bottom:1px solid #151c21;text-align:left;white-space:nowrap}.table th{font-size:7px;color:var(--dim);letter-spacing:.08em;text-transform:uppercase}
pre{margin:0;background:#06080a;border:1px solid var(--line);border-radius:9px;padding:9px;color:#91a0a8;font:8px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;max-height:220px;overflow:auto}.footer{padding:12px 2px 18px;color:#46535c;font-size:7px;letter-spacing:.07em;text-transform:uppercase;display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap}
@media(max-width:1100px){.matrix{grid-template-columns:repeat(2,minmax(0,1fr))}.detailGrid{grid-template-columns:1fr}.bottomGrid{grid-template-columns:1fr}}
@media(max-width:700px){.top{align-items:flex-start;flex-direction:column;gap:8px}.topbar{width:100%;justify-content:flex-start;overflow:auto;flex-wrap:nowrap}.chip{flex:0 0 auto}.hero{grid-template-columns:1fr}.sessionBox{min-width:0}.shell{padding:9px}.hero{padding:13px}.hero h1{font-size:23px}.hero p{font-size:11px}.matrix{grid-template-columns:1fr}.tile{padding:11px}.tileGrid{grid-template-columns:repeat(2,1fr)}.kpis{grid-template-columns:repeat(2,1fr)}.detailCols{grid-template-columns:1fr}.price{font-size:34px}.forecastSignal{font-size:25px}.toolbar{margin-top:8px}.btn,select{font-size:11px;padding:9px 11px}.auto{font-size:10px}.table table{font-size:9px}.table th{font-size:8px}}
</style>
</head>
<body>
<header class="top">
<div class="brand"><div class="g">G</div><div><div class="name">GORILA ARGENTUM</div><div class="sub">advanced research signal terminal · Argentina</div></div></div>
<div class="topbar"><span id="live" class="chip">CONNECTING</span><span id="session" class="chip">BYMA · —</span><span id="storage" class="chip">POSTGRES · —</span><span id="gate" class="chip bad">GATE · BLOCKED</span><button id="refresh" class="btn">REFRESH</button><a class="btn" href="/docs">API</a></div>
</header>
<main class="shell">
<section class="hero"><div>
<div class="kicker">Primary research instrument</div><h1>ARGENTINA SIGNAL MATRIX</h1>
<p>Señal de investigación auditable para renta variable argentina. La fuerza de señal combina probabilidad del motor, evidencia OOS, consenso multihorizonte, frescura de datos, shadow outcomes y drift. No concede autoridad de ejecución.</p>
<div class="toolbar"><select id="ticker"></select><button id="hardRefresh" class="btn">RECALCULATE</button><label class="auto"><input id="auto" type="checkbox" checked> refresh 5 s</label><span id="matrixMeta" class="chip">MATRIX · —</span></div>
</div>
<div class="sessionBox"><div class="sessionTop"><div class="sessionTitle">BYMA session</div><span id="sessionBadge" class="chip">—</span></div><div id="sessionValue" class="sessionVal">—</div><div id="sessionMeta" class="sessionMeta">—</div></div>
</section>

<div class="sectionHead"><div><div class="sectionTitle">Universe · GGAL · BMA · YPFD · PAMP · TGSU2 · CEPU</div><div class="sectionSub">selecciona una tarjeta para abrir el detalle completo</div></div><div id="matrixTime" class="sectionSub">—</div></div>
<section id="matrix" class="matrix"></section>

<section class="chartCard">
<div class="chartHeader">
  <div class="chartIdentity"><span id="chartSymbol" class="chartSymbol">GGAL</span><span id="chartLast" class="chartLast">—</span><span id="chartMove" class="chartMove flat">—</span></div>
  <div class="chartControls">
    <span id="chartResolution" class="chip">—</span>
    <button class="rangeBtn active" data-range="1D">1D</button>
    <button class="rangeBtn" data-range="5D">5D</button>
    <button class="rangeBtn" data-range="1M">1M</button>
    <button class="rangeBtn" data-range="3M">3M</button>
    <button class="rangeBtn" data-range="6M">6M</button>
    <button class="rangeBtn" data-range="1Y">1Y</button>
  </div>
</div>
<div class="chartShell">
  <canvas id="priceCanvas"></canvas>
  <div id="chartTooltip" class="chartTooltip"></div>
  <div id="chartEmpty" class="chartEmpty">NO MARKET SERIES</div>
</div>
<div class="chartFooter">
  <span id="chartCoverage">—</span>
  <span id="chartUpdated">—</span>
</div>
</section>

<section class="detail"><div class="detailHead"><div><div class="detailTitle">Signal detail</div><div id="detailSub" class="sectionSub">—</div></div><span id="detailState" class="sig neutral">—</span></div><div class="detailBody">
<div class="detailGrid">
<div class="primary"><div class="primaryTop"><div><div id="dSymbol" class="sym">—</div><div id="dPrice" class="price">—</div><div id="dPriceMeta" class="priceMeta">—</div></div><div class="forecast"><div class="forecastLabel">Research signal</div><div id="dSignal" class="forecastSignal">—</div><div id="dProb" class="prob">P(UP) —</div></div></div>
<div class="kpis"><div class="kpi"><small>Signal score</small><b id="dScore">—</b></div><div class="kpi"><small>Confidence</small><b id="dConf">—</b></div><div class="kpi"><small>Edge</small><b id="dEdge">—</b></div><div class="kpi"><small>Data grade</small><b id="dGrade">—</b></div></div>
<div class="detailCols"><div class="box"><h3>Market state</h3><div class="row"><span class="muted">Bid / Ask</span><b id="dBidAsk">—</b></div><div class="row"><span class="muted">Spread</span><b id="dSpread">—</b></div><div class="row"><span class="muted">Data age</span><b id="dAge">—</b></div><div class="row"><span class="muted">Source</span><b id="dSource">—</b></div><div class="row"><span class="muted">Quote time</span><b id="dQuoteTime">—</b></div><div class="row"><span class="muted">BCRA FX</span><b id="dBcraFx">—</b></div><div class="row"><span class="muted">Reservas</span><b id="dBcraReserves">—</b></div><div class="row"><span class="muted">Base monetaria</span><b id="dBcraBase">—</b></div><div class="row"><span class="muted">BADLAR / TAMAR</span><b id="dBcraRates">—</b></div></div>
<div class="box"><h3>Structure</h3><div class="row"><span class="muted">1 bar</span><b id="m1">—</b></div><div class="row"><span class="muted">3 bars</span><b id="m3">—</b></div><div class="row"><span class="muted">5 bars</span><b id="m5">—</b></div><div class="row"><span class="muted">10 bars</span><b id="m10">—</b></div><div class="row"><span class="muted">Trend Z</span><b id="mTrend">—</b></div></div></div>
<div class="box" style="margin-top:9px"><h3>Multi-horizon consensus</h3><div id="horizons" class="horizon"></div></div>
</div>
<div class="box"><h3>Precision evidence</h3><div class="row"><span class="muted">OOS status</span><b id="vStatus">—</b></div><div class="row"><span class="muted">Accuracy</span><b id="vAcc">—</b></div><div class="row"><span class="muted">Brier</span><b id="vBrier">—</b></div><div class="row"><span class="muted">Brier skill</span><b id="vSkill">—</b></div><div class="row"><span class="muted">Log loss</span><b id="vLogloss">—</b></div><div class="row"><span class="muted">OOS N</span><b id="vN">—</b></div><h3 style="margin-top:14px">Risk controls</h3><div class="row"><span class="muted">Drift</span><b id="rDrift">—</b></div><div class="row"><span class="muted">PSI</span><b id="rPsi">—</b></div><div class="row"><span class="muted">Shadow accuracy</span><b id="rShadow">—</b></div><div id="flags" style="margin-top:8px"></div></div>
</div></div></section>

<details class="diagnostics">
<summary>
  <span class="diagnosticsTitle"><span>SYSTEM DIAGNOSTICS</span><span id="diagnosticSummary" class="diagnosticsMeta">HEALTHY · DETAILS HIDDEN</span></span>
  <span class="diagnosticsMeta">runtime · sources · shadow · promotion</span>
</summary>
<div class="diagnosticsBody">
<section class="bottomGrid"><div class="box"><h3>System state</h3><div class="row"><span class="muted">Runtime tick</span><b id="runtime">—</b></div><div class="row"><span class="muted">Autonomous cycle</span><b id="autonomous">—</b></div><div class="row"><span class="muted">Snapshot engine</span><b id="snapshotState">—</b></div><div class="row"><span class="muted">Circuit breaker</span><b id="circuit">—</b></div><div class="row"><span class="muted">Shadow</span><b id="shadow">—</b></div><div class="row"><span class="muted">Promotion</span><b id="promotion">—</b></div></div>
<div class="box"><h3>Data fabric</h3><div class="table"><table><thead><tr><th>source</th><th>status</th><th>rows</th><th>latency</th><th>last success</th></tr></thead><tbody id="sources"></tbody></table></div></div></section>
<section class="box" style="margin-top:10px"><h3>Runtime telemetry</h3><pre id="telemetry">{}</pre></section>
</div>
</details>
<footer class="footer"><span>RESEARCH ONLY · TRADING EXECUTION DISABLED · AUTOMATIC PROMOTION OFF</span><span>FULL DIAGNOSTICS AVAILABLE ABOVE</span></footer>
</main>
<script>
const $=id=>document.getElementById(id);
const fmt=(v,d=3)=>v===null||v===undefined||v===''?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=(v,d=1)=>v===null||v===undefined||Number.isNaN(Number(v))?'—':(Number(v)*100).toFixed(d)+'%';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let selected='GGAL',selectionVersion=0,chartTimeframe='1D',chartRows=[],alphaMap={};
let matrixBusy=false,controlBusy=false,chartRequestId=0;

async function json(url,opts={}){const timeoutMs=opts.timeoutMs??12000;const retries=opts.retries??2;let lastError=null;for(let attempt=0;attempt<=retries;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const fetchOpts={...opts,cache:'no-store',signal:controller.signal};delete fetchOpts.timeoutMs;delete fetchOpts.retries;const r=await fetch(url,fetchOpts);const contentType=r.headers.get('content-type')||'';const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error('Non-JSON '+url)}if(!r.ok){const err=new Error(d?.detail||('HTTP '+r.status));err.httpStatus=r.status;throw err}if(!contentType.includes('application/json'))throw new Error('Non-JSON '+url);return d}catch(e){lastError=e?.name==='AbortError'?new Error('TIMEOUT '+url):e;if(lastError.httpStatus===429)break;const retryable=attempt<retries;if(!retryable)break;await new Promise(resolve=>setTimeout(resolve,500*Math.pow(2,attempt)))}finally{clearTimeout(timer)}}throw lastError||new Error('REQUEST_FAILED '+url)}
function chip(el,text,kind){el.textContent=text;el.className='chip '+(kind||'')}
function stateClass(signal){return signal==='UP'?'up':signal==='DOWN'?'down':signal==='NEUTRAL'?'neutral':signal==='NO_DATA'?'na':'na'}
function displayStatus(item){return item?.status==='NO_DATA'?'FORECAST UNAVAILABLE':item?.status==='BLOCKED'?'BLOCKED':item?.signal||'—'}
function renderSession(m){const s=m?.argentina_session||{};const open=!!s.open;chip($('session'),'BYMA · '+(open?'OPEN':'CLOSED'),open?'good':'warn');chip($('sessionBadge'),open?'OPEN':'CLOSED',open?'good':'warn');$('sessionValue').textContent=open?'NEGOCIACIÓN ABIERTA':'MERCADO CERRADO';$('sessionMeta').textContent=(s.local_time||'—')+' · '+(s.regular_window?.open||'—')+'–'+(s.regular_window?.close||'—')}
function tile(item){const sel=(item.symbol===selected?' sel':'')+(item.status==='NO_DATA'?' noData':'');const statusLabel=displayStatus(item);const sig=stateClass(item.status==='NO_DATA'?'NO_DATA':item.signal);const rawScore=item.signal_score;const score=rawScore==null?null:Number(rawScore);const safeScore=Number.isFinite(score)?score:0;const p=item.probability?.up;const age=item.market?.market_age_seconds ?? item.market?.engine_age_seconds;const forecastAge=item.market?.forecast_age_seconds;const grade=item.market?.data_grade||'—';const a=alphaMap[item.symbol]||{};return '<div class="tile'+sel+'" data-symbol="'+esc(item.symbol)+'"><div class="tileTop"><div><div class="sym">'+esc(item.symbol)+'</div><div style="font-size:7px;color:#53616b;letter-spacing:.08em;text-transform:uppercase;margin-top:2px">V2 relative alpha</div></div><span class="sig '+sig+'">'+esc(statusLabel)+'</span></div><div class="scoreRow"><div><div class="scoreLabel">research signal score</div><div class="bar"><i style="width:'+Math.max(0,Math.min(100,safeScore))+'%"></i></div></div><div class="score">'+(Number.isFinite(score)?score.toFixed(1):'—')+'</div></div><div class="tileGrid"><div class="mini"><small>P(UP)</small><b>'+pct(p)+'</b></div><div class="mini"><small>V2 P(RES UP)</small><b>'+pct(a.p_residual_up)+'</b></div><div class="mini"><small>V2 RANK</small><b>'+(a.rank??'—')+'</b></div><div class="mini"><small>DATA</small><b>'+esc(grade)+'</b></div></div><div class="tileFoot"><span>'+esc(a.direction||(item.status==='NO_DATA'?'FORECAST UNAVAILABLE':item.status)||'—')+'</span><span>quote '+(age==null?'—':fmt(age,0)+'s')+' · model '+(forecastAge==null?'—':fmt(forecastAge,0)+'s')+'</span></div></div>'}
function selectSymbol(symbol){selected=symbol;selectionVersion++;$('ticker').value=selected;$('chartSymbol').textContent=selected;$('chartResolution').textContent='LOADING';$('chartCoverage').textContent='requesting market series…';$('chartUpdated').textContent='—';$('chartTooltip').style.display='none';$('chartEmpty').textContent='LOADING '+selected;drawChart([]);renderDetailPlaceholder(selected);refreshDetail(selected,selectionVersion);refreshLive(selected,selectionVersion);refreshChart(selected,selectionVersion)}
function renderDetailPlaceholder(symbol){$('dSymbol').textContent=symbol||'—';$('dPrice').textContent='—';$('dPriceMeta').textContent='loading snapshot · '+new Date().toLocaleTimeString();$('dSignal').textContent='—';$('dProb').textContent='P(UP) — · P(DOWN) —';$('dScore').textContent='—';$('dConf').textContent='—';$('dEdge').textContent='—';$('dGrade').textContent='—';$('dBidAsk').textContent='— / —';$('dSpread').textContent='—';$('dAge').textContent='—';$('dSource').textContent='—';$('dQuoteTime').textContent='—';for(const id of ['m1','m3','m5','m10','mTrend','vStatus','vAcc','vBrier','vSkill','vLogloss','vN','rDrift','rPsi','rShadow'])$(id).textContent='—';$('horizons').innerHTML='<div class="h">loading…</div>';$('flags').innerHTML='<div class="row"><span class="muted">state</span><b class="warnText">LOADING</b></div>';$('detailState').textContent='LOADING';$('detailState').className='sig neutral';$('detailSub').textContent=symbol+' · snapshot request'}
function renderMatrix(m){const items=m.items||[];if(!items.some(x=>x.symbol===selected)&&items.length)selectSymbol(items[0].symbol);$('ticker').innerHTML=items.map(x=>'<option>'+esc(x.symbol)+'</option>').join('');$('ticker').value=selected;$('matrix').innerHTML=items.map(tile).join('');[...document.querySelectorAll('.tile')].forEach(el=>el.addEventListener('click',()=>selectSymbol(el.dataset.symbol)));const c=m.counts||{};$('matrixMeta').textContent='MATRIX · '+(c.total??items.length)+' · FORECAST UNAVAILABLE '+(c.no_data??0)+' · WATCH '+(c.watch??0);$('matrixTime').textContent='updated '+new Date().toLocaleTimeString();renderSession(m)}
function renderLive(l){if(!l)return;const q=l.quote||{};const eventAge=l.event_age_seconds??l.age_seconds;const transportAge=l.transport_age_seconds;if(q.last!==null&&q.last!==undefined)$('dPrice').textContent=fmt(q.last,4);if(q.quoteTimestamp)$('dPriceMeta').textContent=(q.source||'MARKET DATA')+' · '+q.quoteTimestamp;$('dAge').textContent=eventAge==null?'—':fmt(eventAge,1)+' s';$('dQuoteTime').textContent=q.quoteTimestamp||'—';$('dSource').textContent=q.source||'—';if(l.status==='LIVE')chip($('live'),'LIVE DATA','good');else if(l.status==='DELAYED'){const mins=eventAge==null?'—':(eventAge/60).toFixed(1);chip($('live'),'MARKET DATA · DELAYED '+mins+'m','warn')}else if(l.status==='STALE')chip($('live'),'MARKET DATA · STALE','bad');else if(l.status==='MARKET_CLOSED')chip($('live'),'MARKET CLOSED','warn');else if(l.status==='INVALID_TIMESTAMP')chip($('live'),'MARKET DATA · INVALID TIME','bad');else if(l.status==='NO_PROFESSIONAL_FEED')chip($('live'),'LIVE FEED NOT CONFIGURED','bad');else if(l.status==='NO_LIVE_CACHE')chip($('live'),'NO LIVE FEED','bad')}
function renderBcra(b){const i=b?.items||{};const fx=i.BCRA_WHOLESALE_FX||{};const reserves=i.BCRA_RESERVAS_USD||{};const base=i.BCRA_BASE_MONETARIA||{};const badlar=i.BCRA_BADLAR_NA||{};const tamar=i.BCRA_TAMAR_NA||{};$("dBcraFx").textContent=fx.value==null?"—":fmt(fx.value,4)+" ARS/USD · "+(fx.direction_20d||"—");$("dBcraReserves").textContent=reserves.value==null?"—":fmt(reserves.value,0)+" USD mm · "+(reserves.direction_20d||"—");$("dBcraBase").textContent=base.value==null?"—":fmt(base.value,0)+" ARS mm · "+(base.direction_20d||"—");$("dBcraRates").textContent=(badlar.value==null?"—":fmt(badlar.value,2)+" / ")+(tamar.value==null?"—":fmt(tamar.value,2)+" % n.a.");}function renderDetail(d){$('dSymbol').textContent=d.symbol||'—';$('dPrice').textContent=fmt(d.market?.last,4);$('dPriceMeta').textContent=(d.market?.source||'—')+' · '+(d.market?.quote_timestamp||'—');const sig=d.status==='NO_DATA'?'FORECAST UNAVAILABLE':(d.signal||'—');$('dSignal').textContent=sig;$('dSignal').className='forecastSignal '+(sig==='UP'?'goodText':sig==='DOWN'?'badText':sig==='FORECAST UNAVAILABLE'?'muted':'warnText');$('dProb').textContent='P(UP) '+pct(d.probability?.up)+' · P(DOWN) '+pct(d.probability?.down);$('dScore').textContent=fmt(d.signal_score,1);$('dConf').textContent=pct(d.probability?.confidence);$('dEdge').textContent=pct(d.probability?.edge);$('dGrade').textContent=d.market?.data_grade||'—';$('dBidAsk').textContent=fmt(d.market?.bid,4)+' / '+fmt(d.market?.ask,4);$('dSpread').textContent=fmt(d.market?.spread_bps,2)+' bps';$('dAge').textContent=d.market?.market_event_age_seconds==null?(d.market?.market_age_seconds==null?'—':fmt(d.market.market_age_seconds,1)+' s'):fmt(d.market.market_event_age_seconds,1)+' s';$('dSource').textContent=d.market?.source||'—';$('dQuoteTime').textContent=d.market?.quote_timestamp||'—';const st=d.structure||{};$('m1').textContent=pct(st.return_1,2);$('m3').textContent=pct(st.return_3,2);$('m5').textContent=pct(st.return_5,2);$('m10').textContent=pct(st.return_10,2);$('mTrend').textContent=fmt(st.trend_z,2);const h=d.multi_horizon?.horizons||{};$('horizons').innerHTML=Object.entries(h).map(([k,x])=>'<div class="h">'+esc(k)+'s <b>'+pct(x?.latest_forecast?.p_up)+'</b></div>').join('')||'<div class="h">—</div>';const forecastAvailable=d.probability?.up!==null&&d.probability?.up!==undefined;
$('vStatus').textContent=forecastAvailable?(d.validation?.validated?'VALIDATED':'RESEARCH / NOT VALIDATED'):'NOT SCORED · FORECAST UNAVAILABLE';
$('vStatus').className=forecastAvailable?(d.validation?.validated?'goodText':'warnText'):'warnText';$('vAcc').textContent=pct(d.validation?.accuracy);$('vBrier').textContent=fmt(d.validation?.brier,5);$('vSkill').textContent=fmt(d.validation?.brier_skill,5);$('vLogloss').textContent=fmt(d.validation?.log_loss,5);$('vN').textContent=fmt(d.validation?.oos_count,0);$('rDrift').textContent=d.drift?.status||'—';$('rPsi').textContent=fmt(d.drift?.psi,2);$('rShadow').textContent=pct(d.shadow?.accuracy);const flags=d.risk_flags||[];
const flagLabels={
 NO_FORECAST:'FORECAST UNAVAILABLE',
 MODEL_NOT_VALIDATED:'NO VALIDATED FORECAST EVIDENCE',
 DATA_NOT_FRESH:'MARKET / FORECAST DATA STALE',
 MARKET_DATA_DELAYED:'MARKET DATA DELAYED',
 MARKET_DATA_STALE:'MARKET DATA STALE',
 MARKET_DATA_INVALID_TIMESTAMP:'MARKET DATA TIMESTAMP INVALID',
 DRIFT_ALERT:'DRIFT ALERT',
 DRIFT_UNAVAILABLE:'DRIFT MONITOR UNAVAILABLE'
};
$('flags').innerHTML=flags.length?flags.map(f=>'<div class="row"><span class="muted">flag</span><b class="badText">'+esc(flagLabels[f]||f)+'</b></div>').join(''):'<div class="row"><span class="muted">flags</span><b class="goodText">NONE</b></div>';$('detailState').textContent=d.status==='NO_DATA'?'FORECAST UNAVAILABLE':(d.status||'—');$('detailState').className='sig '+stateClass(d.status==='NO_DATA'?'NO_DATA':d.signal);$('detailSub').textContent=(d.symbol||'—')+' · '+(d.status==='NO_DATA'?'forecast unavailable · no validated forecast bound to this snapshot':('research-only · '+(d.actionable?'armed research':'not actionable')))}
function resizeCanvas(canvas){const rect=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:rect.width,h:rect.height}}
function drawChart(rows){const canvas=$('priceCanvas');const tip=$('chartTooltip');if(!canvas)return;const {ctx,w,h}=resizeCanvas(canvas);ctx.clearRect(0,0,w,h);const points=(rows||[]).filter(r=>Number.isFinite(Number(r.close)));if(!points.length){$('chartEmpty').style.display='flex';$('chartResolution').textContent='NO DATA';return}
$('chartEmpty').style.display='none';const left=54,right=14,top=14,bottom=28,pw=Math.max(1,w-left-right),ph=Math.max(1,h-top-bottom);const values=points.map(r=>Number(r.close));let min=Math.min(...values),max=Math.max(...values);if(min===max){const pad=Math.max(Math.abs(min)*0.001,1);min-=pad;max+=pad}else{const pad=(max-min)*0.08;min-=pad;max+=pad}
const x=i=>left+(i/(Math.max(1,points.length-1)))*pw;const y=v=>top+(1-(v-min)/(max-min))*ph;
ctx.strokeStyle='rgba(48,62,72,.55)';ctx.lineWidth=1;ctx.setLineDash([]);
for(let i=0;i<=4;i++){const yy=top+(i/4)*ph;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();const val=max-((max-min)*(i/4));ctx.fillStyle='#62727d';ctx.font='9px Inter,system-ui,sans-serif';ctx.textAlign='left';ctx.fillText(Number(val).toLocaleString('en-US',{maximumFractionDigits:4}),6,yy+3)}
for(let i=0;i<=4;i++){const ix=Math.min(points.length-1,Math.round((i/4)*(points.length-1)));const xx=x(ix);ctx.strokeStyle='rgba(38,50,59,.28)';ctx.beginPath();ctx.moveTo(xx,top);ctx.lineTo(xx,h-bottom);ctx.stroke();ctx.fillStyle='#52616b';ctx.font='8px Inter,system-ui,sans-serif';ctx.textAlign='center';const d=new Date(points[ix].time);ctx.fillText(Number.isNaN(d.getTime())?String(points[ix].time):d.toLocaleDateString('es-AR',{month:'short',day:'numeric'}),xx,h-9)}
const grad=ctx.createLinearGradient(0,top,0,h-bottom);grad.addColorStop(0,'rgba(99,227,255,.22)');grad.addColorStop(1,'rgba(99,227,255,0)');
ctx.beginPath();points.forEach((p,i)=>{const xx=x(i),yy=y(Number(p.close));if(i===0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)});ctx.lineTo(x(points.length-1),h-bottom);ctx.lineTo(x(0),h-bottom);ctx.closePath();ctx.fillStyle=grad;ctx.fill();
ctx.beginPath();points.forEach((p,i)=>{const xx=x(i),yy=y(Number(p.close));if(i===0)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)});ctx.strokeStyle='#63ddff';ctx.lineWidth=2;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();
const lx=x(points.length-1),ly=y(values[values.length-1]);ctx.fillStyle='#63ddff';ctx.beginPath();ctx.arc(lx,ly,3.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dff9ff';ctx.font='9px Inter,system-ui,sans-serif';ctx.textAlign='right';ctx.fillText(Number(values.at(-1)).toLocaleString('en-US',{maximumFractionDigits:4}),w-right,Math.max(top+9,ly-7));
canvas._chart={points,left,top,pw,ph,x,y,min,max,w,h};
}
function bindChartPointer(){const canvas=$('priceCanvas');if(!canvas||canvas._bound)return;canvas._bound=true;canvas.addEventListener('mousemove',ev=>{const state=canvas._chart;if(!state?.points?.length)return;const rect=canvas.getBoundingClientRect();const px=Math.max(state.left,Math.min(state.w-14,ev.clientX-rect.left));const idx=Math.round(((px-state.left)/state.pw)*(state.points.length-1));const p=state.points[Math.max(0,Math.min(state.points.length-1,idx))];const xx=state.x(Math.max(0,Math.min(state.points.length-1,idx)));const yy=state.y(Number(p.close));drawChart(state.points);const ctx=canvas.getContext('2d');ctx.save();ctx.strokeStyle='rgba(210,236,245,.25)';ctx.lineWidth=1;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(xx,state.top);ctx.lineTo(xx,state.h-28);ctx.stroke();ctx.beginPath();ctx.moveTo(state.left,yy);ctx.lineTo(state.w-14,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#e9fbff';ctx.beginPath();ctx.arc(xx,yy,3.5,0,Math.PI*2);ctx.fill();ctx.restore();const tip=$('chartTooltip');const d=new Date(p.time);tip.innerHTML='<b>'+Number(p.close).toLocaleString('en-US',{maximumFractionDigits:4})+'</b><small>'+ (Number.isNaN(d.getTime())?String(p.time):d.toLocaleString('es-AR')) +'</small>';tip.style.display='block';tip.style.left=Math.min(rect.width-165,Math.max(8,px+12))+'px';tip.style.top=Math.min(rect.height-68,Math.max(8,yy-20))+'px'});
canvas.addEventListener('mouseleave',()=>{$('chartTooltip').style.display='none';drawChart(chartRows)});
}
function renderChartMeta(d){$('chartSymbol').textContent=d.symbol||selected;$('chartLast').textContent=d.last==null?'—':fmt(d.last,4);
if(d.last!=null&&$('dPrice').textContent==='—'){$('dPrice').textContent=fmt(d.last,4);$('dPriceMeta').textContent='CHART CLOSE · '+(d.resolution||'—')+' · '+(d.coverage?.end||'—')}
const ch=d.change_pct;const cls=ch>0?'up':ch<0?'down':'flat';$('chartMove').className='chartMove '+cls;$('chartMove').textContent=ch==null?'—':((ch>=0?'+':'')+pct(ch,2));$('chartResolution').textContent=(d.resolution||'—')+' · '+(d.bars||0)+' bars';const fs=d.freshness||{};const age=fs.event_age_seconds;if(fs.status==='DELAYED'){$('chartCoverage').textContent=(d.coverage?.start||'—')+' → '+(d.coverage?.end||'—')+' · delayed '+(age==null?'—':fmt(age/60,1)+'m')}else if(fs.status==='STALE'){$('chartCoverage').textContent=(d.coverage?.start||'—')+' → '+(d.coverage?.end||'—')+' · STALE'}else{$('chartCoverage').textContent=(d.coverage?.start||'—')+' → '+(d.coverage?.end||'—')};$('chartUpdated').textContent='fetched '+new Date().toLocaleTimeString()+' · event '+(d.coverage?.end||'—');document.querySelectorAll('.rangeBtn').forEach(b=>b.classList.toggle('active',b.dataset.range===chartTimeframe));}
async function refreshChart(requestedSymbol=selected,version=selectionVersion){const requestId=++chartRequestId;try{const d=await json('/api/gorila/chart/'+encodeURIComponent(requestedSymbol)+'?timeframe='+encodeURIComponent(chartTimeframe));if(requestId!==chartRequestId||version!==selectionVersion||requestedSymbol!==selected)return;chartRows=d.rows||[];renderChartMeta(d);drawChart(chartRows);bindChartPointer()}catch(e){if(requestId===chartRequestId&&version===selectionVersion){chartRows=[];drawChart([]);$('chartResolution').textContent='ERROR';$('chartCoverage').textContent='chart API unavailable'}}}
async function refreshMatrix(){if(matrixBusy)return;matrixBusy=true;try{const [d,a]=await Promise.all([json('/api/gorila/signal-matrix'),json('/api/gorila/cross-sectional').catch(()=>null)]);alphaMap={};(a?.items||[]).forEach(x=>alphaMap[x.symbol]=x);renderMatrix(d);chip($('matrixMeta'),(a?.evidence?.validation_status||'V2 '+(a?.status||'UNKNOWN'))+' · V2 5D',a?.evidence?.validation_status==='VALIDATED_RESEARCH'?'good':'warn')}catch(e){$('telemetry').textContent='Transient matrix API error; automatic retry active · '+String(e)}finally{matrixBusy=false}}
async function refreshDetail(requestedSymbol=selected,version=selectionVersion){try{const [d,b]=await Promise.all([json('/api/gorila/signal/'+encodeURIComponent(requestedSymbol)),json('/api/gorila/bcra').catch(()=>null)]);if(version!==selectionVersion||requestedSymbol!==selected)return;renderDetail(d);if(b)renderBcra(b)}catch(e){if(version===selectionVersion){$('detailSub').textContent=requestedSymbol+' · retrying snapshot';$('telemetry').textContent='Transient detail API error; automatic retry active · '+String(e)}}}
async function refreshControl(){try{const s=await json('/api/gorila/control'),h=s.health||{},p=s.promotion?.current_evaluation||{},sh=s.shadow||{},rt=(s.runtime?.items||[])[0];chip($('storage'),h.database?.ready?'POSTGRES · READY':'POSTGRES · DEGRADED',h.database?.ready?'good':'bad');chip($('gate'),'GATE · '+(p.status||'BLOCKED'),p.status==='ELIGIBLE'?'good':'bad');$('runtime').textContent=rt?.status||'—';$('autonomous').textContent=h.autonomous_runtime?.status||'—';const ss=h.argentina_signals||{};$('snapshotState').textContent=(ss.updated_symbols!=null?ss.updated_symbols+'/6 · ':'')+(ss.status||'—');const readiness=(rt?.result?.audit||{}).readiness||{};$('circuit').textContent=readiness.circuit_breaker||'—';$('shadow').textContent=(sh.settled??0)+' settled / '+(sh.predictions??0)+' total · '+pct(sh.accuracy);$('promotion').textContent=p.status||'BLOCKED';$('sources').innerHTML=(h.sources||[]).map(x=>'<tr><td>'+esc(x.source)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.rows_last_batch)+'</td><td>'+fmt(x.latency_ms,1)+' ms</td><td>'+esc(x.last_success_at||'—')+'</td></tr>').join('');$('telemetry').textContent=JSON.stringify({health:h,promotion:s.promotion,shadow:sh,runtime:s.runtime},null,2);const breaker=readiness.circuit_breaker||'—';const cycle=h.autonomous_runtime?.status||'—';const pg=h.database?.ready?'POSTGRES READY':'POSTGRES DEGRADED';$('diagnosticSummary').textContent=pg+' · '+String(cycle).toUpperCase()+' · CIRCUIT '+String(breaker).toUpperCase()}catch(e){$('telemetry').textContent='Transient control API error; automatic retry active · '+String(e);if($('diagnosticSummary'))$('diagnosticSummary').textContent='DIAGNOSTICS · RETRYING'}}
$('ticker').addEventListener('change',e=>selectSymbol(e.target.value));document.querySelectorAll('.rangeBtn').forEach(btn=>btn.addEventListener('click',()=>{chartTimeframe=btn.dataset.range||'1D';refreshChart(selected,selectionVersion)}));window.addEventListener('resize',()=>drawChart(chartRows));
$('hardRefresh').addEventListener('click',()=>{refreshMatrix();refreshDetail(selected,selectionVersion);refreshControl();refreshLive(selected,selectionVersion);refreshChart(selected,selectionVersion)});
$('refresh').addEventListener('click',()=>{refreshMatrix();refreshDetail(selected,selectionVersion);refreshControl();refreshLive(selected,selectionVersion);refreshChart(selected,selectionVersion)});
const pollers={matrix:null,detail:null,control:null,live:null,chart:null};function stopPollers(){for(const k of Object.keys(pollers)){if(pollers[k])clearTimeout(pollers[k]);pollers[k]=null}}function startPoll(name,fn,ms){if(pollers[name])clearTimeout(pollers[name]);const run=async()=>{if(!$('auto').checked)return;try{await fn()}finally{if($('auto').checked)pollers[name]=setTimeout(run,ms)}};run()}$('auto').addEventListener('change',e=>{stopPollers();if(e.target.checked){startPoll('matrix',refreshMatrix,15000);startPoll('detail',()=>refreshDetail(selected,selectionVersion),10000);startPoll('control',refreshControl,15000);startPoll('live',()=>refreshLive(selected,selectionVersion),2500);startPoll('chart',()=>refreshChart(selected,selectionVersion),5000)}});
async function refreshLive(requestedSymbol=selected,version=selectionVersion){try{const l=await json('/api/gorila/live/'+encodeURIComponent(requestedSymbol));if(version!==selectionVersion||requestedSymbol!==selected)return;renderLive(l)}catch(e){if(version===selectionVersion)chip($('live'),'RECONNECTING','warn')}}
(async()=>{await Promise.allSettled([refreshMatrix(),refreshDetail(selected,selectionVersion),refreshControl(),refreshLive(selected,selectionVersion),refreshChart(selected,selectionVersion)]);if($('auto').checked){startPoll('matrix',refreshMatrix,15000);startPoll('detail',()=>refreshDetail(selected,selectionVersion),10000);startPoll('control',refreshControl,15000);startPoll('live',()=>refreshLive(selected,selectionVersion),2500);startPoll('chart',()=>refreshChart(selected,selectionVersion),5000)}})();
</script>
<!-- Compatibility markers preserved:
     /api/drift?limit=50
     /api/control
     /api/shadow/summary
     DRIFT MONITOR
     CONTROL ROOM — BATCH 13
     SHADOW LEDGER — BATCH 14
-->
</body></html>""")
