"""PMSF-X Nano — professional cross-fitted multi-horizon meta validation.

Research-only. Specialist probabilities for 300s/900s/1800s are generated by
strict chronological walk-forward fits first. Those OOS probabilities are then
used as leakage-safe meta-features in a second walk-forward layer. This avoids
the expensive repeated nested refits of the first prototype while preserving
point-in-time separation at both specialist and meta levels.
"""

from __future__ import annotations

import math
import random
from datetime import datetime, timedelta, timezone
from typing import Any

from quant.temporal import TemporalSample, walk_forward_splits

HORIZONS: tuple[tuple[int, int], ...] = (
    (300, 1),
    (900, 3),
    (1800, 6),
)
PRIMARY_HORIZON_SECONDS = 300
SPECIALIST_TRAIN_SIZE = 300
SPECIALIST_TEST_SIZE = 60
META_TRAIN_SIZE = 300
META_TEST_SIZE = 60
PRIMARY_PURGE_MINUTES = 5
PRIMARY_EMBARGO_MINUTES = 5
BOOTSTRAPS = 1000
BLOCK_LENGTH = 10
MIN_META_FOLDS = 5
MIN_OOS_COUNT = 300
ECE_BINS = 10
LOGISTIC_STEPS = 64
META_LOGISTIC_STEPS = 72


def _clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def _safe_float(value: Any) -> float | None:
    try:
        value = float(value)
    except (TypeError, ValueError):
        return None
    return value if math.isfinite(value) else None


def _parse_time(value: Any) -> datetime | None:
    if not value:
        return None
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return None


def _bars(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for row in rows:
        ts = _parse_time(row.get("date") or row.get("timestamp"))
        o = _safe_float(row.get("open"))
        h = _safe_float(row.get("high"))
        lo = _safe_float(row.get("low"))
        c = _safe_float(row.get("close"))
        v = _safe_float(row.get("volume")) or 0.0
        if ts is None or None in (o, h, lo, c) or c <= 0 or h < lo:
            continue
        out.append({
            "time": ts,
            "open": o,
            "high": h,
            "low": lo,
            "close": c,
            "volume": v,
        })
    out.sort(key=lambda x: x["time"])
    return out


def _feature_map(rows: list[dict[str, Any]]) -> dict[datetime, list[float]]:
    bars = _bars(rows)
    expected = timedelta(minutes=5)
    out: dict[datetime, list[float]] = {}
    for i in range(3, len(bars)):
        if not (
            bars[i]["time"] - bars[i - 1]["time"] == expected
            and bars[i - 1]["time"] - bars[i - 2]["time"] == expected
            and bars[i - 2]["time"] - bars[i - 3]["time"] == expected
        ):
            continue

        b0, b1, b3 = bars[i], bars[i - 1], bars[i - 3]
        c0, c1, c3 = b0["close"], b1["close"], b3["close"]
        range_bps = (b0["high"] - b0["low"]) / c0 * 10000.0
        close_position = (
            (c0 - b0["low"]) / (b0["high"] - b0["low"]) - 0.5
            if b0["high"] > b0["low"]
            else 0.0
        )
        volume_change = (
            math.log1p(b0["volume"] + 1.0)
            - math.log1p(b1["volume"] + 1.0)
        )

        out[b0["time"]] = [
            _clamp((c0 / c1 - 1.0) * 10000.0 / 25.0, -3.0, 3.0),
            _clamp((c0 / c3 - 1.0) * 10000.0 / 50.0, -3.0, 3.0),
            _clamp(range_bps / 100.0, 0.0, 3.0),
            _clamp(close_position, -0.5, 0.5),
            _clamp(volume_change, -3.0, 3.0),
        ]
    return out


def _target_samples(
    rows: list[dict[str, Any]],
    *,
    horizon_bars: int,
    feature_map: dict[datetime, list[float]],
    threshold_bps: float = 0.5,
) -> list[TemporalSample]:
    bars = _bars(rows)
    expected = timedelta(minutes=5)
    samples: list[TemporalSample] = []

    for i in range(3, len(bars) - horizon_bars):
        required = range(i - 2, i + horizon_bars + 1)
        if any(
            bars[j]["time"] - bars[j - 1]["time"] != expected
            for j in required
            if j > 0
        ):
            continue

        future_return_bps = (
            bars[i + horizon_bars]["close"] / bars[i]["close"] - 1.0
        ) * 10000.0
        if abs(future_return_bps) < threshold_bps:
            continue

        feature = feature_map.get(bars[i]["time"])
        if feature is None:
            continue

        samples.append(
            TemporalSample(
                event_time=bars[i]["time"],
                label_end_time=bars[i + horizon_bars]["time"],
                features=feature,
                label=1 if future_return_bps > 0 else 0,
            )
        )
    return samples


def _sigmoid(x: float) -> float:
    x = _clamp(x, -30.0, 30.0)
    return 1.0 / (1.0 + math.exp(-x))


def _fit_logistic(
    samples: list[TemporalSample],
    *,
    feature_count: int,
    steps: int,
    learning_rate: float = 0.06,
    l2: float = 0.02,
) -> list[float]:
    weights = [0.0] * (feature_count + 1)
    if not samples:
        return weights

    n = len(samples)
    for _ in range(steps):
        grad = [0.0] * len(weights)
        for sample in samples:
            x = sample.features
            z = weights[0] + sum(
                weights[j + 1] * x[j] for j in range(feature_count)
            )
            error = _sigmoid(z) - sample.label
            grad[0] += error
            for j in range(feature_count):
                grad[j + 1] += error * x[j]

        for j in range(len(weights)):
            grad[j] /= n
            if j > 0:
                grad[j] += l2 * weights[j]
            weights[j] -= learning_rate * grad[j]

    return weights


def _predict(weights: list[float], features: list[float]) -> float:
    return _sigmoid(
        weights[0]
        + sum(weights[j + 1] * features[j] for j in range(len(features)))
    )


def _specialist_oos_predictions(
    samples: list[TemporalSample],
    *,
    horizon_minutes: int,
) -> dict[datetime, float]:
    folds = walk_forward_splits(
        samples,
        train_size=SPECIALIST_TRAIN_SIZE,
        test_size=SPECIALIST_TEST_SIZE,
        purge=timedelta(minutes=horizon_minutes),
        embargo=timedelta(minutes=horizon_minutes),
    )
    predictions: dict[datetime, float] = {}
    for fold in folds:
        train = list(fold.train)
        if len({sample.label for sample in train}) < 2:
            continue
        weights = _fit_logistic(
            train,
            feature_count=5,
            steps=LOGISTIC_STEPS,
        )
        for sample in fold.test:
            predictions[sample.event_time] = _predict(
                weights,
                list(sample.features),
            )
    return predictions


def _fit_meta(
    features: list[list[float]],
    labels: list[int],
) -> list[float]:
    samples = [
        TemporalSample(
            event_time=i,
            label_end_time=i,
            features=x,
            label=y,
        )
        for i, (x, y) in enumerate(zip(features, labels))
    ]
    return _fit_logistic(
        samples,
        feature_count=3,
        steps=META_LOGISTIC_STEPS,
        learning_rate=0.05,
        l2=0.05,
    )


def _meta_predict(weights: list[float], features: list[float]) -> float:
    return _predict(weights, features)


def _logloss(probability: float, label: int) -> float:
    p = _clamp(probability, 1e-6, 1.0 - 1e-6)
    return -(label * math.log(p) + (1 - label) * math.log(1.0 - p))


def _ece(probabilities: list[float], labels: list[int]) -> float | None:
    if not labels:
        return None
    total = len(labels)
    error = 0.0
    for bucket in range(ECE_BINS):
        lo = bucket / ECE_BINS
        hi = (bucket + 1) / ECE_BINS
        indices = [
            i for i, p in enumerate(probabilities)
            if (lo <= p < hi) or (
                bucket == ECE_BINS - 1 and p <= hi
            )
        ]
        if not indices:
            continue
        avg_p = sum(probabilities[i] for i in indices) / len(indices)
        avg_y = sum(labels[i] for i in indices) / len(indices)
        error += len(indices) / total * abs(avg_p - avg_y)
    return error


def _metrics(
    probabilities: list[float],
    labels: list[int],
    baseline: list[float],
) -> dict[str, float | int | None]:
    n = max(1, len(labels))
    brier = sum((p - y) ** 2 for p, y in zip(probabilities, labels)) / n
    baseline_brier = (
        sum((p - y) ** 2 for p, y in zip(baseline, labels)) / n
    )
    logloss = sum(
        _logloss(p, y) for p, y in zip(probabilities, labels)
    ) / n
    baseline_logloss = sum(
        _logloss(p, y) for p, y in zip(baseline, labels)
    ) / n
    accuracy = sum(
        (p >= 0.5) == bool(y)
        for p, y in zip(probabilities, labels)
    ) / n

    return {
        "test_count": len(labels),
        "accuracy": accuracy,
        "brier": brier,
        "baseline_brier": baseline_brier,
        "brier_skill": (
            1.0 - brier / baseline_brier
            if baseline_brier > 0
            else None
        ),
        "log_loss": logloss,
        "baseline_log_loss": baseline_logloss,
        "log_loss_delta": baseline_logloss - logloss,
        "ece": _ece(probabilities, labels),
    }


def _block_bootstrap_delta(
    model_a: list[float],
    model_b: list[float],
    labels: list[int],
    *,
    seed: int,
) -> dict[str, float | int | None]:
    n = len(labels)
    if n < BLOCK_LENGTH:
        return {
            "iterations": 0,
            "delta_brier_ci_low": None,
            "delta_brier_ci_high": None,
        }

    rng = random.Random(seed)
    deltas: list[float] = []
    block_count = math.ceil(n / BLOCK_LENGTH)
    starts = list(range(n))

    for _ in range(BOOTSTRAPS):
        indices: list[int] = []
        for _ in range(block_count):
            start = rng.choice(starts)
            indices.extend(
                (start + k) % n
                for k in range(BLOCK_LENGTH)
            )
        indices = indices[:n]

        brier_a = sum(
            (model_a[i] - labels[i]) ** 2 for i in indices
        ) / n
        brier_b = sum(
            (model_b[i] - labels[i]) ** 2 for i in indices
        ) / n
        deltas.append(brier_b - brier_a)

    deltas.sort()
    return {
        "iterations": BOOTSTRAPS,
        "delta_brier_ci_low": deltas[int(0.025 * len(deltas))],
        "delta_brier_ci_high": deltas[int(0.975 * len(deltas)) - 1],
    }


def _meta_samples(
    specialist_predictions: dict[int, dict[datetime, float]],
    primary_samples: list[TemporalSample],
) -> list[TemporalSample]:
    common_times = set.intersection(
        *(set(predictions) for predictions in specialist_predictions.values())
    )
    samples: list[TemporalSample] = []

    for sample in primary_samples:
        if sample.event_time not in common_times:
            continue
        samples.append(
            TemporalSample(
                event_time=sample.event_time,
                label_end_time=sample.label_end_time,
                features=[
                    specialist_predictions[300][sample.event_time],
                    specialist_predictions[900][sample.event_time],
                    specialist_predictions[1800][sample.event_time],
                ],
                label=sample.label,
            )
        )
    return samples


def validate_multi_horizon_meta(
    rows: list[dict[str, Any]],
    *,
    symbol: str | None = None,
    bootstrap_seed: int = 20260924,
) -> dict[str, Any]:
    feature_map = _feature_map(rows)
    samples_by_horizon = {
        seconds: _target_samples(
            rows,
            horizon_bars=horizon_bars,
            feature_map=feature_map,
        )
        for seconds, horizon_bars in HORIZONS
    }

    primary_samples = samples_by_horizon[PRIMARY_HORIZON_SECONDS]
    minimum_rows = SPECIALIST_TRAIN_SIZE + SPECIALIST_TEST_SIZE
    if len(primary_samples) < minimum_rows:
        return {
            "status": "INSUFFICIENT_DATA",
            "validated": False,
            "validation_type": "cross_fitted_walk_forward_purged_embargoed",
            "symbol": symbol,
            "sample_counts": {
                str(seconds): len(samples)
                for seconds, samples in samples_by_horizon.items()
            },
            "production_eligible": False,
        }

    specialist_predictions: dict[int, dict[datetime, float]] = {}
    for horizon_seconds, _ in HORIZONS:
        specialist_predictions[horizon_seconds] = _specialist_oos_predictions(
            samples_by_horizon[horizon_seconds],
            horizon_minutes=horizon_seconds // 60,
        )

    meta_samples = _meta_samples(
        specialist_predictions,
        primary_samples,
    )
    if len(meta_samples) < META_TRAIN_SIZE + META_TEST_SIZE:
        return {
            "status": "INSUFFICIENT_CROSS_FIT_META_DATA",
            "validated": False,
            "validation_type": "cross_fitted_walk_forward_purged_embargoed",
            "symbol": symbol,
            "sample_counts": {
                str(seconds): len(samples)
                for seconds, samples in samples_by_horizon.items()
            },
            "cross_fitted_meta_count": len(meta_samples),
            "production_eligible": False,
        }

    meta_folds = walk_forward_splits(
        meta_samples,
        train_size=META_TRAIN_SIZE,
        test_size=META_TEST_SIZE,
        purge=timedelta(minutes=PRIMARY_PURGE_MINUTES),
        embargo=timedelta(minutes=PRIMARY_EMBARGO_MINUTES),
    )

    fold_results: list[dict[str, Any]] = []
    for fold in meta_folds:
        train = list(fold.train)
        test = list(fold.test)
        if len({sample.label for sample in train}) < 2:
            continue

        train_x = [list(sample.features) for sample in train]
        train_y = [sample.label for sample in train]
        weights = _fit_meta(train_x, train_y)

        probabilities = [
            _meta_predict(weights, list(sample.features))
            for sample in test
        ]
        specialist_300 = [float(sample.features[0]) for sample in test]
        labels = [sample.label for sample in test]
        baseline_rate = sum(train_y) / len(train_y)
        baseline = [baseline_rate] * len(labels)

        fold_results.append({
            "fold": fold.fold,
            "meta_train_count": len(train),
            "test_count": len(test),
            "meta_train_positive_rate": baseline_rate,
            "metrics": _metrics(probabilities, labels, baseline),
            "primary_300s_metrics": _metrics(
                specialist_300,
                labels,
                baseline,
            ),
            "probabilities": probabilities,
            "specialist_300_probabilities": specialist_300,
            "labels": labels,
        })

    if not fold_results:
        return {
            "status": "NO_USABLE_META_FOLDS",
            "validated": False,
            "validation_type": "cross_fitted_walk_forward_purged_embargoed",
            "symbol": symbol,
            "meta_fold_count": len(meta_folds),
            "usable_fold_count": 0,
            "production_eligible": False,
        }

    probabilities = [
        p for fold in fold_results for p in fold["probabilities"]
    ]
    specialist_300 = [
        p
        for fold in fold_results
        for p in fold["specialist_300_probabilities"]
    ]
    labels = [
        y for fold in fold_results for y in fold["labels"]
    ]
    baselines = [
        rate
        for fold in fold_results
        for rate in [fold["meta_train_positive_rate"]] * fold["test_count"]
    ]

    metrics = _metrics(probabilities, labels, baselines)
    specialist_metrics = _metrics(
        specialist_300,
        labels,
        baselines,
    )
    baseline = baselines
    model_vs_baseline_bootstrap = _block_bootstrap_delta(
        probabilities,
        baseline,
        labels,
        seed=bootstrap_seed,
    )
    model_vs_300_bootstrap = _block_bootstrap_delta(
        probabilities,
        specialist_300,
        labels,
        seed=bootstrap_seed + 1,
    )

    delta_brier_vs_300s = (
        specialist_metrics["brier"] - metrics["brier"]
    )
    gate_reasons: list[str] = []

    if len(fold_results) < MIN_META_FOLDS:
        gate_reasons.append("INSUFFICIENT_META_FOLDS")
    if len(labels) < MIN_OOS_COUNT:
        gate_reasons.append("INSUFFICIENT_OOS_COUNT")
    if metrics["brier_skill"] is None or metrics["brier_skill"] <= 0:
        gate_reasons.append("NO_POSITIVE_BRIER_SKILL")
    if (
        model_vs_baseline_bootstrap["delta_brier_ci_low"] is None
        or model_vs_baseline_bootstrap["delta_brier_ci_low"] <= 0
    ):
        gate_reasons.append("BOOTSTRAP_CI_VS_BASELINE_INCLUDES_ZERO")
    if (
        model_vs_300_bootstrap["delta_brier_ci_low"] is None
        or model_vs_300_bootstrap["delta_brier_ci_low"] <= 0
    ):
        gate_reasons.append("BOOTSTRAP_CI_VS_PRIMARY_300S_INCLUDES_ZERO")
    if metrics["log_loss_delta"] <= 0:
        gate_reasons.append("NO_LOGLOSS_IMPROVEMENT")
    if metrics["ece"] is None or metrics["ece"] > 0.05:
        gate_reasons.append("ECE_ABOVE_0_05")

    validated = not gate_reasons

    return {
        "status": "VALIDATED" if validated else "RESEARCH_PASS_PENDING_GATE",
        "validated": validated,
        "validation_type": "cross_fitted_walk_forward_purged_embargoed",
        "symbol": symbol,
        "target_horizon_seconds": PRIMARY_HORIZON_SECONDS,
        "sample_counts": {
            str(seconds): len(samples)
            for seconds, samples in samples_by_horizon.items()
        },
        "specialist_oos_counts": {
            str(seconds): len(predictions)
            for seconds, predictions in specialist_predictions.items()
        },
        "cross_fitted_meta_count": len(meta_samples),
        "meta_fold_count": len(meta_folds),
        "usable_fold_count": len(fold_results),
        "oos_count": len(labels),
        "metrics": metrics,
        "primary_300s_metrics": specialist_metrics,
        "delta_brier_vs_300s": delta_brier_vs_300s,
        "bootstrap": model_vs_baseline_bootstrap,
        "primary_300s_bootstrap": model_vs_300_bootstrap,
        "folds": [
            {
                "fold": fold["fold"],
                "meta_train_count": fold["meta_train_count"],
                "test_count": fold["test_count"],
                "metrics": fold["metrics"],
                "primary_300s_metrics": fold["primary_300s_metrics"],
            }
            for fold in fold_results
        ],
        "gate": {
            "minimum_meta_folds": MIN_META_FOLDS,
            "minimum_oos_count": MIN_OOS_COUNT,
            "maximum_ece": 0.05,
            "bootstrap": "paired moving-block bootstrap",
            "block_length": BLOCK_LENGTH,
            "bootstrap_iterations": BOOTSTRAPS,
            "criteria": [
                "positive Brier skill vs fold-local expanding-rate baseline",
                "95% block-bootstrap CI lower bound > 0 vs baseline",
                "95% block-bootstrap CI lower bound > 0 vs standalone 300s",
                "positive log-loss improvement",
                "ECE <= 0.05",
            ],
            "reasons": gate_reasons,
        },
        "selection": {
            "pre_specified_trials": 1,
            "multiple_testing_adjustment": "single pre-specified candidate",
        },
        "production_eligible": False,
        "note": (
            "Research validation only. The production probability and trigger "
            "are never modified by this result."
        ),
    }
